### ISSUE TITLE
Events Pagination and Get/Update/Delete an Individual Event

### ISSUE THREAD

**Issue by jamesmstone** [SocalNick/orchestrate-php-client#12]
Hi I was wondering whether the API features shown here are supported? https://orchestrate.io/blog/2014/04/24/updatedeventsapi/

**Comment by SocalNick** [comment]
Looks like I implemented the PUT and LIST operations and missed this blog post. I'll try to get this in soon.

**Comment by jamesmstone** [comment]
Thanks, greatly appreciated

**Comment by SocalNick** [comment]
@jamesmstone - I've implemented all the missing features from the Event API. I've only pushed to master as I need to document before pushing a 0.5.0 tag. Would you be able to test in the meantime?

Check out the unit test to see how it works: https://github.com/SocalNick/orchestrate-php-client/blob/master/tests/EventTest.php

**Comment by jamesmstone** [comment]
Thanks so much for the quick implementation, I'll start testing it now. I'll be sure to let you know if I come across anything. Thanks again

**Comment by SocalNick** [comment]
@jamesmstone - added getNext() to the EventListObject. I'll be drafting a release in a few minutes.
