### ISSUE TITLE
Possibility to edit the client base_url without passing an entire Guzzle client instance

### ISSUE THREAD

**Issue by izziaraffaele** [SocalNick/orchestrate-php-client#13]
Expose base_url parameter just like you do for the ApiKey

**Comment by SocalNick** [comment]
@izziaraffaele - is this to support the alternate AWS?
Amazon EU West	Ireland	https://api.aws-eu-west-1.orchestrate.io/

**Comment by SocalNick** [comment]
@izziaraffaele - i made the change on master. could you test?

I need to document it and some other backwards compatibility changes before pushing a version 0.5.0.

**Comment by SocalNick** [comment]
@izziaraffaele - published 0.5.0 with this fix: https://github.com/SocalNick/orchestrate-php-client/releases/tag/0.5.0
