### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by hursey013** [SocalNick/orchestrate-php-client#16]
I am beginner when it comes to development, so my apologies if this is a silly question.  I am curious if you have any best practices when it comes to error handling.  For example, when I attempt to fetch a key that does not exist I get:

    Fatal error: Uncaught exception 'GuzzleHttp\Exception\ClientException' with message 'Client error response [url] https://api.orchestrate.io/v0/test/0b47f371d420dcd [status code] 404 [reason phrase] Not Found'

Should I be using exceptions (try...catch)?  Thanks for your help and for putting this library together.

**Comment by koxon** [comment]
Yes try catch is the way

On Wed, Jul 15, 2015 at 3:09 PM, Brian Hurst <notifications@github.com>
wrote:

> I am beginner when it comes to development, so my apologies if this is a
> silly question. I am curious if you have any best practices when it comes
> to error handling. For example, when I attempt to fetch a key that does not
> exist I get:
>
> Fatal error: Uncaught exception 'GuzzleHttp\Exception\ClientException' with message 'Client error response [url] https://api.orchestrate.io/v0/test/0b47f371d420dcd [status code] 404 [reason phrase] Not Found'
>
> Should I be using exceptions (try...catch)? Thanks for your help and for
> putting this library together.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SocalNick/orchestrate-php-client/issues/16>.
>



-- 
Nicolas Menciere
Co-Founder and CTO
Sport Archive Inc.
