### ISSUE TITLE
Parenthesis issue

### ISSUE THREAD

**Issue by sportarc** [SocalNick/orchestrate-php-client#9]
Hi Nicholas,

I've been doing some tests with Search and discovered that adding parenthesis to the search query doesn't work.
 
For example:
value.id:fencing OR beach_volley OR martial_arts OR FFBS OR tennis_table
This will work

value.id:(fencing OR beach_volley OR martial_arts OR FFBS OR tennis_table)
This will not work even though it is a valid syntax using the Orchestrate Console. 

I was looking into the encoding and discovered that http_buil_query also encode "()" even though they are valid characters after "?". 
It is issue. 

I tested by hand:
This works:
curl "https://api.orchestrate.io/v0/channels?query=value.id%3A(fencing+OR+beach_volley+OR+martial_arts+OR+FFBS+OR+tennis_table)&limit=5&offset=0" -u 'xxxx'

This doesn't work:
curl "https://api.orchestrate.io/v0/channels?query=value.id%3A%28fencing+OR+beach_volley+OR+martial_arts+OR+FFBS+OR+tennis_table%28&limit=5&offset=0" -u 'xxxx'
Result: {"message":"The search query provided is invalid.","code":"search_query_malformed"}

Let me know what you think, but I believe we may want to raise this issue to Orchestrate team so they also allow encoded ().

Nick

**Comment by izziaraffaele** [comment]
Could you please add/suggest a quick fix for it while you decide what to do?

**Comment by sportarc** [comment]
Yes. Please close this issue. I found the problem.

On Fri, Jan 16, 2015 at 12:29 PM, Raffaele <notifications@github.com> wrote:

> Could you please add/suggest a quick fix for it while you decide what to
> do?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SocalNick/orchestrate-php-client/issues/9#issuecomment-70289512>
> .
>



-- 
Nicolas Menciere
Founder and CTO
Sport Archive Inc.

**Comment by sportarc** [comment]
It was actually caused by the request itself, the format was wrong to begin
with ...

On Fri, Jan 16, 2015 at 1:02 PM, Nicolas Menciere <nmenciere@sportarchive.tv
> wrote:

> Yes. Please close this issue. I found the problem.
>
> On Fri, Jan 16, 2015 at 12:29 PM, Raffaele <notifications@github.com>
> wrote:
>
>> Could you please add/suggest a quick fix for it while you decide what to
>> do?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/SocalNick/orchestrate-php-client/issues/9#issuecomment-70289512>
>> .
>>
>
>
>
> --
> Nicolas Menciere
> Founder and CTO
> Sport Archive Inc.
>



-- 
Nicolas Menciere
Founder and CTO
Sport Archive Inc.
